[program:crmeb-workerman]
directory=/var/www/CRMEB/current/crmeb
command=/usr/bin/php think workerman start
autostart=true
autorestart=true
startsecs=5
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/crmeb/workerman.log
stderr_logfile=/var/log/crmeb/workerman.err.log
