[program:crmeb-queue]
directory=/var/www/CRMEB/current/crmeb
command=/usr/bin/php think queue:listen --queue
autostart=true
autorestart=true
startsecs=5
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/crmeb/queue.log
stderr_logfile=/var/log/crmeb/queue.err.log
