<?php

namespace crmeb\services\sms\storage;

use crmeb\basic\BaseSms;

class Aliyun extends BaseSms
{

    protected function initialize(array $config)
    {
        parent::initialize($config); // TODO: Change the autogenerated stub
    }

    public function send(string $phone, string $templateId, array $data = [])
    {
        // TODO: Implement send() method.
    }
}